module.exports = {
  HTTP_STATUS: {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    TOO_MANY_REQUESTS: 429,
    INTERNAL_SERVER_ERROR: 500,
  },
  MESSAGES: {
    NOT_IMPLEMENTED: 'Not implemented yet',
    UNAUTHORIZED: 'Unauthorized',
    FORBIDDEN: 'Forbidden',
    NOT_FOUND: 'Resource not found',
    VALIDATION_ERROR: 'Validation failed',
    SERVER_ERROR: 'Internal server error',
  },
  PHONE: {
    country: 'IN',
    dialCode: '+91',
    countryDigits: 2,
    countryDigitsCode: '91',
    nationalLength: 10,
    nationalPattern: /^[6-9]\d{9}$/,
  },
  OTP_PURPOSE: {
    LOGIN: 'login',
  },
  BOOKING: {
    TIMEZONE: 'Asia/Kolkata',
    REQUEST_EXPIRY_MINUTES: Number(process.env.BOOKING_REQUEST_EXPIRY_MINUTES) || 30,
    PLATFORM_FEE_PERCENT: Number(process.env.PLATFORM_FEE_PERCENT) || 15,
    MAX_NOTE: 500,
    MAX_RENTAL_DAYS: 62,
    CREATE_LIMIT: 10,
    CREATE_WINDOW_MS: 15 * 60 * 1000,
    CURRENCY: 'INR',
    PAYMENT_EXPIRY_MINUTES: Number(process.env.BOOKING_PAYMENT_EXPIRY_MINUTES) || 30,
    RESERVED_STATUSES: ['PENDING_OWNER_APPROVAL', 'PAYMENT_REQUIRED', 'CONFIRMED', 'ACTIVE', 'RETURN_PENDING'],
  },
};
