const TEMPLATES = {
  BOOKING_REQUEST_RECEIVED: {
    category: 'BOOKING',
    priority: 'NORMAL',
    title: 'New booking request',
    message: 'Someone requested to rent your outfit.',
    action: 'OPEN_BOOKING',
  },
  BOOKING_REQUEST_ACCEPTED: {
    category: 'BOOKING',
    priority: 'NORMAL',
    title: 'Booking request accepted',
    message: 'The owner accepted your rental request.',
    action: 'OPEN_BOOKING',
  },
  BOOKING_REQUEST_REJECTED: {
    category: 'BOOKING',
    priority: 'NORMAL',
    title: 'Booking request declined',
    message: 'The owner declined this rental request.',
    action: 'OPEN_BOOKING',
  },
  BOOKING_CANCELLED: {
    category: 'BOOKING',
    priority: 'HIGH',
    title: 'Booking cancelled',
    message: 'A rental request was cancelled.',
    action: 'OPEN_BOOKING',
  },
  BOOKING_EXPIRED: {
    category: 'BOOKING',
    priority: 'HIGH',
    title: 'Booking expired',
    message: 'A rental request expired before it was confirmed.',
    action: 'OPEN_BOOKING',
  },
  BOOKING_PAYMENT_REQUIRED: {
    category: 'PAYMENT',
    priority: 'HIGH',
    title: 'Payment required',
    message: 'Your booking was accepted. Complete payment to confirm the rental.',
    action: 'OPEN_PAYMENT',
  },
  BOOKING_PAYMENT_COMPLETED: {
    category: 'PAYMENT',
    priority: 'NORMAL',
    title: 'Payment completed',
    message: 'Payment was completed for a Pehenlo rental.',
    action: 'OPEN_BOOKING',
  },
  BOOKING_CONFIRMED: {
    category: 'BOOKING',
    priority: 'NORMAL',
    title: 'Booking confirmed',
    message: 'This rental is confirmed.',
    action: 'OPEN_BOOKING',
  },
  PAYMENT_REQUIRED: {
    category: 'PAYMENT',
    priority: 'HIGH',
    title: 'Payment required',
    message: 'Complete payment to confirm your rental.',
    action: 'OPEN_PAYMENT',
  },
  PAYMENT_SUCCESS: {
    category: 'PAYMENT',
    priority: 'NORMAL',
    title: 'Payment completed',
    message: 'Payment was completed for your Pehenlo rental.',
    action: 'OPEN_PAYMENT',
  },
  PAYMENT_FAILED: {
    category: 'PAYMENT',
    priority: 'HIGH',
    title: 'Payment failed',
    message: 'The payment could not be completed. You can try again from the booking.',
    action: 'OPEN_PAYMENT',
  },
  PAYMENT_EXPIRED: {
    category: 'PAYMENT',
    priority: 'HIGH',
    title: 'Payment window expired',
    message: 'The time to pay for this rental has ended.',
    action: 'OPEN_BOOKING',
  },
  EARNING_CREATED: {
    category: 'EARNING',
    priority: 'NORMAL',
    title: 'Earning recorded',
    message: 'A rental earning was added to your account.',
    action: 'OPEN_EARNING',
  },
  EARNING_AVAILABLE: {
    category: 'EARNING',
    priority: 'NORMAL',
    title: 'Earning available',
    message: 'A rental earning is now available for payout.',
    action: 'OPEN_EARNING',
  },
  PAYOUT_REQUESTED: {
    category: 'EARNING',
    priority: 'NORMAL',
    title: 'Payout requested',
    message: 'Your payout request was received. It is not paid yet.',
    action: 'OPEN_PAYOUT',
  },
  PAYOUT_PAID: {
    category: 'EARNING',
    priority: 'NORMAL',
    title: 'Payout paid',
    message: 'A payout was marked paid.',
    action: 'OPEN_PAYOUT',
  },
  PAYOUT_FAILED: {
    category: 'EARNING',
    priority: 'HIGH',
    title: 'Payout failed',
    message: 'A payout could not be completed. The amount returns to your available balance.',
    action: 'OPEN_PAYOUT',
  },
  REVIEW_RECEIVED: {
    category: 'REVIEW',
    priority: 'LOW',
    title: 'New review',
    message: 'You received a review from a completed rental.',
    action: 'OPEN_REVIEW',
  },
  LISTING_SUBMITTED: {
    category: 'LISTING',
    priority: 'NORMAL',
    title: 'Listing submitted',
    message: 'Your outfit was submitted for review before it appears in Explore.',
    action: 'OPEN_LISTING',
  },
  REPORT_RECEIVED: {
    category: 'SAFETY',
    priority: 'NORMAL',
    title: 'Report received',
    message: 'We received your report. It does not change the booking or payment.',
    action: 'OPEN_SAFETY',
  },
  WELCOME: {
    category: 'ACCOUNT',
    priority: 'LOW',
    title: 'Welcome to Pehenlo',
    message: 'Your account is ready. Booking and payment updates will appear here.',
    action: 'OPEN_NOTIFICATIONS',
  },
  PROFILE_UPDATED: {
    category: 'ACCOUNT',
    priority: 'LOW',
    title: 'Profile updated',
    message: 'Your profile changes were saved.',
    action: 'OPEN_PROFILE',
  },
};

function getTemplate(type) {
  return TEMPLATES[type] || null;
}

module.exports = { TEMPLATES, getTemplate };
